/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HYao' at '3/27/17 1:17 PM' with Gradle 2.14.1
 *
 * @author HYao, @date 3/27/17 1:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
